### ISSUE TITLE
Vivaldi Browser not identified

### ISSUE THREAD

**Issue by andreaspixsy** [flowkey/meteor-bowser#1]
Thanks to this software being unaware of Vivaldi Browser, I cannot use flowkey 👎

**Comment by nerdmed** [comment]
@andreaspixsy oh wow you found the responsible package. I really understand your frustration and i apologize for the inconvenience. Unfortunately there are too many browsers to optimize the performance for all of them.

I would suggest you to use chrome or if you want an open source browser you can try out [chromium](https://www.chromium.org/)

**Comment by andreaspixsy** [comment]
But vivaldi is using chromium!

Here is my user agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.92 Safari/537.36 Vivaldi/1.6.689.32`

**Comment by nerdmed** [comment]
@andreaspixsy Oh ok, strange that it is not passing. Maybe we can fix this in https://github.com/ded/bowser - we are only wrapping this package for meteor

**Comment by andreaspixsy** [comment]
I just checked, bowser fully supports vivaldi. I guess this wrapper just needs to update to latest bowser?
